name: Run Tests Before Merge

on:
  pull_request:
    branches:
      - master  # Change this to match your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22  # Adjust based on your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...
